{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <pytest_allure_test.TestClass object at 0x0000020801189608>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\npython_allure_test\\pytest_allure_test.py:10: AssertionError"}, "start": 1594530714244, "stop": 1594530714244, "uuid": "c7e05799-2b15-4163-a23c-cc463243ac2c", "historyId": "e24c77d6b2cdc902a3ebbca687f2bd5c", "testCaseId": "7c065375bd932aaf8cfea915386df158", "fullName": "python_allure_test.pytest_allure_test.TestClass#test_two", "labels": [{"name": "parentSuite", "value": "python_allure_test"}, {"name": "suite", "value": "pytest_allure_test"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-B7H4EKN"}, {"name": "thread", "value": "46968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "python_allure_test.pytest_allure_test"}]}